export class NomenclatureEtablissement {
    codeEtab!: string
    libeEtab!: string
    codeTypeEtab!: string
    matrFisc!: string
    codeSect!: string
    codeZoneHabi!: string
    codeDele!: string
    codeCommEtab!: string
    numeDeciOuve!: string
    dateDemaActi!: string
    dateDeciOuve!: string
    dateDepoCahiChar!: string
    depoCahiCharPrep!: string
    dateCrea!: string
    dateCreaBD!: string
    nomPrenFond!: string
    codeGenrFond!: string
    numePiecIden!: string
    dateDeliv!: string
    dateNaisFond!: string
    lieuNaisFond!: string
    adrePersFond!: string
    codePostFond!: string
    codeDeleFond!: string
    codeComm!: string
    codeNiveEtud!: string
    codeDipl!: string
    codeSituFami!: string
    nombEnfa!: string
    prof!: string
    tele!: string
    email!: string
    numeEtab!: string
    codeEtatEtab!: string
    adreEtab!: string
    codePostEtab!: string
    codeMiniFond!: string
    dateFerm!: string
    causFerm!: string
    userFerm!: string
    dateVAlFerm!: string
    dateAssurance!: string
    dateMedicine!: string
    positionX!: string
    positionY!: string
}